config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: { registrations: 'registrations' }
  ActiveAdmin.routes(self)
  get 'bookings/create'

  mount Attachinary::Engine => '/attachinary'

  resource :bookings, only: [:create]
  get 'organizations_search', to: 'organizations#search'

  resources :organizations do
    get 'organization_contact', to: 'organizations#organization_contact'
    post 'organization_contact', to: 'organizations#organization_send', as: 'organization_send'
    resources :jobs
    resources :events
  end

  post 'organizations/:id/like', to: 'organizations#like', as: 'like_organization'

  post 'articles/:id/like', to: 'articles#like', as: 'like_article'

  root to: 'pages#home'
  get 'welcome', to: 'pages#welcome'
  get 'dashboard', to: 'pages#dashboard'
  get 'about_us', to: 'pages#about_us'
  get 'developers', to: 'pages#developers'
  get 'events', to: 'pages#events', as: 'events'
  get 'jobs', to: 'pages#jobs', as: 'jobs'

  get 'articles/search', to: 'articles#search'
  get 'articles/tags/:tag', to: 'articles#by_tag'
  resources 'comments', only: [:create, :destroy]
  resources 'articles', only: [:show, :index]
end

app/models/article.rb
class Article < ApplicationRecord
  extend FriendlyId
  friendly_id :title, use: :history

  acts_as_taggable
  scope :without_current, ->(id) { where.not(id: id) }
  scope :published, -> { where(is_published: true).order(published_at: :desc) }
  scope :published_without_main, -> { where(is_published: true, is_main_article: false).order(published_at: :desc) }
  scope :main_article, -> { where(is_main_article: true) }
  before_save :check_for_publication_status
  before_save :set_main_article
  has_attachment :photo, accept: [:jpg, :png, :gif]
  acts_as_commentable
  acts_as_votable
  belongs_to :user

  def suggestions
    if tags.blank?
      Article.published.without_current(id).limit(3)
    else
      Article.tagged_with(tags.first).without_current(id).limit(3)
    end
  end

  def self.decide_page(page)
    if !page || page == '1'
      Article.published_without_main.page(1).per(6)
    else
      Article.published_without_main.page(page).per(6)
    end
  end

  def self.search(criteria)
    Article.where('title LIKE ?', "%#{criteria}%")
           .or(Article.where('body LIKE ?', "%#{criteria}%"))
  end

  def self.by_tag(tag)
    Article.tagged_with(tag)
           .where(is_published: true)
  end

  def should_generate_new_friendly_id?
    title_changed?
  end

  private

  def slug_candidates
    [
      :title,
      [:title, :created_at],
      [:title, :description, :created_at]
    ]
  end

  def check_for_publication_status
    if (is_published_was == false) && (is_published == true) && published_at_was.nil?
      self.published_at = Time.zone.now
    end
  end

  def set_main_article
    if (is_main_article_was == false) && (is_main_article == true)
      Article.where.not(id: id).update_all(is_main_article: false)
    end
  end
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  skip_before_action :authenticate_user!, only: [:index, :show, :by_tag, :search]
  before_action :find_article, only: [:show, :like]

  def index
    if !article_params[:page] || article_params[:page] == '1'
      @main_article = Article.includes(:tags).main_article.first
    end
    @articles = Article.includes(:tags).decide_page(article_params[:page])
  end

  def show
    @suggestions = @article.suggestions
  end

  def search
    @articles = Article.by_tag(params[:category]) unless params[:category].blank?
    @articles = Article.search(params[:title]) unless params[:title].blank?
    @articles = @articles.page(article_params[:page] || '1').per(6)
    render template: 'articles/index'
  end

  def like
    @article.liked_by current_user
    redirect_to article_path(@article)
  end

  def by_tag
    @articles = Article.by_tag(article_params[:tag])
                       .page(article_params[:page] || '1').per(6)
    render template: 'articles/index'
  end

  private

  def find_article
    @article = Article.friendly.find(params[:id])  
    if params[:id] != @article.slug && params[:id]&.to_i != @article.id
      redirect_to article_path(@article), status: :moved_permanently 
    end
  end

  def article_params
    params.permit(:id, :page, :tag)
  end
end

app/views/articles/_search_bar.html.erb
<!-- Search bar -->
<%= form_tag articles_search_path, method: :get do %>
<%= text_field_tag 'title', params[:name], placeholder: "  Search articles", class: "text-search-field" %>
<%= select_tag(:category, options_for_select([['Education'], ['Fashion'], ['Waste'], ['Health'], ['Environment'], ['Inclusion'],['Community']]), include_blank: "All categories", class: "text-search-dropdown")%>

<%= submit_tag 'Search', class: "btn-feiy-rec-white"%>
<% end %>

app/views/articles/index.html.erb
<%= cloudinary_js_config %>
<% title "Good Stories" %>
<% description "Discover ideas, people and projects that create a better future!" %>

<!-- Welcome Banner -->
<div class="wrapper index-search-wrapper">
  <div class="index-search-header">
    <div class="index-search-header-welcome text-center">
      <h1>Inspire the Change!</h1>
    </div>
    <div class="tagline-welcome text-center">
      <h3>Discover ideas, people and projects that create a better future</h3>
    </div>
  </div>
  <!-- Search bar -->
  <div id="home-search">
    <%= render 'articles/search_bar'%>
  </div>
</div>


<!-- ORGANIZATIONS SEARCH RESULTS -->
<div class="container">
  <div class="row">
  <% if @main_article %>
    <%if @main_article.photo %>
      <% background_style = "background: url(#{cl_image_path(@main_article.photo.path, :width=>940, :height=>350, :crop=>"fill")}) no-repeat;background-size: cover;"%>
    <% else %>
      <% background_style = "background: url(card_org_ngo_default.jpg) no-repeat;background-size: cover;"%>
    <% end %>
    <%= content_tag :div, class: 'col-xs-12 col-sm-12 col-md-12' do %>
      <%= content_tag :div, class: 'main-article-card', style:background_style do %>
        <% if !@main_article.photo %>
          <%= image_tag "card_org_ngo_default.jpg", class: "organization-card-img" %>
        <% end %>
        <div class="main-article-description">
          <p class="article-category"><%= @main_article.tags.first&.name&.capitalize %></p>
            <p class="main-article-title"><strong><%= @main_article.title %></strong></p>
        </div>
        <div class="article-icons">
          <i class="fa fa-heart main-article-icon"></i>
          <span class="main-article-icon-text"><%= @main_article.votes_for.size %></span>
          <i class="fa fa-commenting main-article-icon"></i>
          <span class="main-article-icon-text"><%= @main_article.comments.size %></span>
        </div>
        <%= link_to "", article_path(@main_article), class: "article-link" %>
      <% end %>
     <%end%>
    <%end%>
    <% @articles.each_with_index do |article, index| %>
        <%= content_tag :div, class: 'col-xs-12 col-sm-6 col-md-6' do %>
        <a href=<%= article_path(article) %> class='article-link'>
          <%= content_tag :div, class: 'article-card-medium' do %>
            <% if article.photo %>
              <img src="<%= cl_image_path(article.photo.path, :width=>1000, height: 562, :crop=>"fill")%>" class='article-img'/>
            <% else %>
              <%= image_tag "card_org_ngo_default.jpg", class: "article-img" %>
            <% end %>
            <div class="article-description">
              <p class="article-category"><%= article.tags.first&.name&.capitalize %></p>
              <p class="article-title"><strong><%= truncate(article.title, length: 73) %></strong></p>
              <p class="article-title-description"><%= truncate(article.description, length: 100) %></p>
            </div>
            <div class="article-icons">
              <i class="fa fa-heart article-icon"></i>
              <span class="article-icon-text"><%= article.votes_for.size %></span>
              <i class="fa fa-commenting article-icon"></i>
              <span class="article-icon-text"><%= article.comments.size %></span>
            </div>
            </a>
          <% end %>
      <% end %>
    <%end%>
    <div class="col-xs-12 col-sm-12 col-md-12 text-center">
      <%= paginate @articles %>
    </div>
  </div>
</div>

app/views/articles/search.html.erb
<% title "Search Organizations" %>

<div class="wrapper index-search-wrapper">
  <div class="index-search-header">
    <div class="index-search-header-welcome text-center">
      <h1>Discover the community<br>of high-impact initiatives<br>in China</h1>
    </div>
  </div>
  <!-- Search bar -->
  <div  class="results-search" >
    <%= render 'search_bar'%>
  </div>
</div>


<!-- ORGANIZATIONS SEARCH RESULTS -->
<div class="text-center results-message">
<% unless @articles.present? %>
  <h4>We haven't found any article matching your search! Please try again!</h4>
<% end %>
</div>
<div class="container">
  <div class="row">
    <% if @articles.present? %>
      <% @articles.each_with_index do |article, index| %>
          <%= content_tag :div, class: 'col-xs-12 col-sm-6 col-md-6' do %>
            <%= content_tag :div, class: 'article-card-medium' do %>
              <% if article.photo %>
                <img src="<%= cl_image_path(article.photo.path, :width=>700, :height=>250, :crop=>"fill")%>" class='article-img' %> tag="<%= article.title %>" >
              <% else %>
                <%= image_tag "card_org_ngo_default.jpg", class: "article-img" %>
              <% end %>
              <div class="article-description">
                <p class="article-category"><%= article.tags.first&.name&.capitalize %></p>
                <p class="article-title"><strong><%= article.title %></strong></p>
                <p class="article-title-description"><%= truncate(article.description, length: 100) %></p>
              </div>
              <div class="article-icons">
                <i class="fa fa-heart article-icon"></i>
                <span class="article-icon-text"><%= article.votes_for.size %></span>
                <i class="fa fa-commenting article-icon"></i>
                <span class="article-icon-text"><%= article.votes_for.size %></span>
              </div>
              <%= link_to "", article_path(article), class: "article-link" %>
            <% end %>
        <% end %>
      <%end%>
      <div class="col-xs-12 col-sm-12 col-md-12 text-center">
        <%= paginate @articles %>
      </div>
    <% end %>
  </div>
</div>

app/views/articles/show.html.erb
<% title @article.title %>

<div itemscope itemtype="http://schema.org/Organization">
  <% if @article.photo %>
    <div class="article-show-banner">
      <%= cl_image_tag @article.photo.path, width: 1440, height: 450, crop: :fill %>
    </div>
  <% else %>
    <div class="org-show-grey-banner"></div>
  <% end %>

  <div class="org-show-banner-content">
    <div class="org-show-banner-content-info">
      <h1 itemprop="name"><%= @article.title %></h1>
      <p><strong>Category:</strong> <%= @article.tags.first&.name&.capitalize %></p>
      <%= social_share_button_tag(@article.title, desc: 'Shared article from feiy.co') %>
      <p><strong><%= @article.votes_for.size %> Likes</strong></p>
    </div>
      <div class="org-show-button-holder">
        <div class: "org-show-update"></div>
        <% if user_signed_in? %>
          <div class="action-like ">
            <%= link_to like_article_path(@article), method: :post do %>
              <%= image_tag "praise.png", class: "org-show-update" %>
            <% end %>
          </div>
        <% else %>
          <div class="action-like ">
            <%= link_to new_user_session_path do %>
              <%= image_tag "praise.png", class: "org-show-update" %>
            <% end %>
          </div>
        <% end %>
      </div>
  </div>

  <div class="article-show-body-content">
    <p class="text-justify"><%= raw(@article.body) %></p>
    <div class="text-right"><%= social_share_button_tag(@article.title, desc: 'Shared article from feiy.co') %></div>
  </div>
</div>

<!-- Read more -->
<div class="container">
  <div class="row">
    <% @suggestions.each do |article| %>
      <div class="col-xs-12 col-sm-6 col-md-4">
        <div class="event-card">
        <% if article.photo %>
          <img src="<%= cl_image_path article.photo.path, height: 180, width: 350, crop: :fill%>" class='events-card-img' tag="<%= article.title %>" >
        <% else %>
          <%= image_tag "card_org_ngo_default.jpg", class: "events-card-img" %>
        <% end %>
          <div class="events-card-description">
            <p id="job-problem"><strong><%= truncate(article.title, length: 20) %></strong></p>
            <p id="job-address"><%= article.created_at.strftime("%B %e, %Y, %l:%M %p ") %></p>
          </div>
          <p class="event-hover-card text-center" id="event-name"><%= article.title %><br><br><%= truncate(article.description, length: 100)%></p>
          <%= link_to "", article_path(article), class: "organization-card-link" %>
        </div>
      </div>
    <% end %>
  </div>
</div>


<!-- comment function -->
<%= render('comments/form', locals: {commentable: @article}) %>
<br/>

<div class='submit_article_to_us'>
  <p><a href="mailto:hi@feiy.co?subject=Submit an article">Submit an article to feiy.co!</a></p>
</div>

<%= render('comments/comments', locals: {commentable: @article}) %>