config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: { registrations: 'registrations' }
  ActiveAdmin.routes(self)
  get 'bookings/create'

  mount Attachinary::Engine => '/attachinary'

  resource :bookings, only: [:create]
  get 'organizations_search', to: 'organizations#search'

  resources :organizations do
    get 'organization_contact', to: 'organizations#organization_contact'
    post 'organization_contact', to: 'organizations#organization_send', as: 'organization_send'
    resources :jobs
    resources :events
  end

  post 'organizations/:id/like', to: 'organizations#like', as: 'like_organization'

  post 'articles/:id/like', to: 'articles#like', as: 'like_article'

  root to: 'pages#home'
  get 'welcome', to: 'pages#welcome'
  get 'dashboard', to: 'pages#dashboard'
  get 'about_us', to: 'pages#about_us'
  get 'developers', to: 'pages#developers'
  get 'events', to: 'pages#events', as: 'events'
  get 'jobs', to: 'pages#jobs', as: 'jobs'

  get 'articles/search', to: 'articles#search'
  get 'articles/tags/:tag', to: 'articles#by_tag'
  resources 'comments', only: [:create, :destroy]
  resources 'articles', only: [:show, :index]
end

app/views/shared/_developers_btn.html.erb
<div class="developers-btn">
  <%= link_to "Meet the developers", developers_path %>
</div>

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <%= notice %>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <%= alert %>
  </div>
<% end %>

app/views/shared/_footer.html.erb
<div id="footer">
  <div class='row'>

    <div class="col-md-2">
      <div id="wechat-qrcode">
        <a href="javascript:void(0);">
          <i class="fa fa-wechat"></i>
          <%= image_tag "feiy-qrcode.jpg" %>
        </a>
      </div>
    </div> 

    <div class="col-md-2">
      <div id="linkedin">
        <a href="https://www.linkedin.com/company/feiy/">
          <i class="fa fa-linkedin"></i>
        </a>
      </div>
    </div> 

    <div class="col-md-2">
      <div id="facebook">
        <a href="https://www.facebook.com/Feiy.co/?hc_ref=ARR-mAekQOYZyDhU8XnEI_q0sUzFx6eJU6D0aqWJhoBUfMyOttstQ0TaGFAWGG30Rlk">
          <i class="fa fa-facebook"></i>
        </a>
      </div>
    </div>

    <div class="col-md-2">
      <div id="twitter">
        <a href="https://twitter.com/FeiyChina">
          <i class="fa fa-twitter"></i>
        </a>
      </div>
    </div>

    <div class="col-md-2">
      <div id="instagram">
        <a href="https://www.instagram.com/feiy_impactlife/">
          <i class="fa fa-instagram"></i>
        </a>
      </div>
    </div>

    <div class="col-md-2">
      <div id="weibo">
        <a href="https://www.weibo.com/u/6286382803">
          <i class="fa fa-weibo"></i>
        </a>
      </div>
    </div>
  </div>
  

  <div class="footer-links">
    <%= link_to "Home", root_path %>
    <%= link_to "About us", about_us_path %>
    <%= mail_to "hi@feiy.co", "Contact" %>
  </div>
  <%= link_to "The Starter Institute", "http://thestarterinstitute.strikingly.com" %>
  <p>© Feiy 2017 - All rights reserved</p>
</div>

app/views/shared/_navbar.html.erb
<div class="navbar-wagon">
  <%= link_to root_path, class: "navbar-feiy-logo" do %>
    <%= image_tag "feiy-logo.svg" %>
  <% end %>
  <div class="list-inline hidden-xs" id="list-left">
    <div class="inline-block dropdown">
      <div class="stories-linkto dropdown-toggle" data-toggle="dropdown">
        Jobs
      </div>
      <ul class="dropdown-menu">
        <li>
          <%= link_to "Find a Job", jobs_path, class: "jobs-linkto" %>
        </li>
        <li>
          <% unless user_signed_in? && current_user.organizations.count == 1 %>
            <%= link_to "Post a Job", new_organization_path, class: "jobs-linkto" %>
          <% else %>
            <%= link_to "Post a Job", new_organization_job_path(current_user.organizations.first), class: "jobs-linkto" %>
          <% end %>
        </li>
      </ul>
    </div>
    <div class="inline-block dropdown">
      <div class="stories-linkto dropdown-toggle" data-toggle="dropdown">
        Events
      </div>
      <ul class="dropdown-menu">
        <li>
          <%= link_to "Find an Event", events_path, class: "jobs-linkto" %>
        </li>
        <li>
          <% unless user_signed_in? && current_user.organizations.count == 1 %>
            <%= link_to "Post an Event", new_organization_path, class: "jobs-linkto" %>
          <% else %>
            <%= link_to "Post an Event", new_organization_event_path(current_user.organizations.first), class: "jobs-linkto" %>
          <% end %>
        </li>
      </ul>
    </div>
    <div class="inline-block">
    <%= link_to "Organizations", organizations_path, class: "organizations-linkto" %>
    </div>
    <div class="inline-block">
    <%= link_to "Stories", articles_path, class: "stories-linkto" %>
    </div>
    <div class="inline-block">
    <%= link_to "Who we are", about_us_path, class: "stories-linkto" %>
    </div>
  </div>

  <!-- Right Navigation -->
  <div class="navbar-wagon-right hidden-xs hidden-sm">

    <!-- Search form -->

    <!-- Text link -->

    <!-- Text link -->

    <!-- Profile picture and dropdown -->
  <div class="navbar-wagon-item">
    <div class="dropdown">
    <% if user_signed_in? && current_user.organizations.count > 0 %>
      <div class="avatar dropdown-toggle" id="navbar-wagon-menu" data-toggle="dropdown">
        <% if current_user.avatar? %>
          <%= cl_image_tag(current_user.avatar.path, {height: 40, width: 40, crop: :fill, gravity: :face, radius: :max, class: "avatar-style", dpr: 2.0}) %>
        <% else %>
          <%= image_tag("profile_placeholder.png", size: '40x40') %>
        <% end %>
      </div>
      <ul class="dropdown-menu dropdown-menu-right navbar-wagon-dropdown-menu">
        <li><%= link_to "Edit Account", edit_user_registration_path %></li>
        <li><%= link_to "Dashboard", dashboard_path %></li>
        <li><%= link_to "Log out", destroy_user_session_path, method: :delete %></li>
      </ul>
    <% elsif user_signed_in? && current_user.organizations.count == 0 %>
      <div class="avatar dropdown-toggle" id="navbar-wagon-menu" data-toggle="dropdown">
        <% if current_user.avatar? %>
          <%= cl_image_tag(current_user.avatar.path, { size: '40x40', radius: :max, crop: :thumb, gravity: :face, dpr: 2.0 }) %>
        <% else %>
          <%= image_tag("profile_placeholder.png", size: '40x40') %>
        <% end %>
      </div>
      <ul class="dropdown-menu dropdown-menu-right navbar-wagon-dropdown-menu">
        <li><%= link_to "Edit Account", edit_user_registration_path %></li>
        <li><%= link_to "Log out", destroy_user_session_path, method: :delete %></li>
      </ul>
      <% else %>
        <ul class="list-inline" id="right-link">
          <li><%= link_to "Sign up", new_user_registration_path, class: "signup-linkto" %></li>
          <li><%= link_to "Sign in", new_user_session_path, class: "signup-linkto" %></li>
        </ul>
    <% end %>
    </div>
  </div>

  <!-- Button (call-to-action) -->
  <!-- Problem this flash alert also appears when I am not trying to create a fourth og -->
  <% unless user_signed_in? && current_user.organizations.count == 1 %>
    <%= link_to "Create Organization", new_organization_path, class: "btn-feiy-primary" %>
  <% end %>
</div>

  <!-- Dropdown appearing on mobile only -->
  <div class="navbar-wagon-item hidden-md hidden-lg">
    <div class="dropdown">
    <% if user_signed_in? && current_user.organizations.count > 0 %>
      <i class="fa fa-bars dropdown-toggle" data-toggle="dropdown"></i>
        <ul class="dropdown-menu dropdown-menu-right navbar-wagon-dropdown-menu">
          <li><%= link_to "Stories", articles_path %></li>
          <li><%= link_to "Organizations", organizations_path %></li>
          <li><%= link_to "Jobs", jobs_path %></li>
          <li><%= link_to "Events", events_path %></li>
          <li><%= link_to "Edit Account", edit_user_registration_path %></li>
          <li><%= link_to "Dashboard", dashboard_path %></li>
          <li><%= link_to "Log out", destroy_user_session_path, method: :delete %></li>
        </ul>
    <% elsif user_signed_in? && current_user.organizations.count == 0 %>
      <i class="fa fa-bars dropdown-toggle" data-toggle="dropdown"></i>
        <ul class="dropdown-menu dropdown-menu-right navbar-wagon-dropdown-menu">
          <li><%= link_to "Stories", articles_path %></li>
          <li><%= link_to "Organizations", organizations_path %></li>
          <li><%= link_to "Create an organization", new_organization_path %></li>
          <li><%= link_to "Jobs", jobs_path %></li>
          <li><%= link_to "Events", events_path %></li>
          <li><%= link_to "Edit Account", edit_user_registration_path %></li>
          <li><%= link_to "Log out", destroy_user_session_path, method: :delete %></li>
        </ul>
    <% else %>
      <i class="fa fa-bars dropdown-toggle" data-toggle="dropdown"></i>
        <ul class="dropdown-menu dropdown-menu-right navbar-wagon-dropdown-menu">
          <li><%= link_to "Stories", articles_path %></li>
          <li><%= link_to "Organizations", organizations_path %></li>
          <li><%= link_to "Create an organization", new_organization_path %></li>
          <li><%= link_to "Sign up", new_user_registration_path %></li>
          <li><%= link_to "Sign in", new_user_session_path %></li>
        </ul>
    <% end %>
    </div>
  </div>
</div>

app/views/shared/_org_likes.html.erb
<div>
  <% if user_signed_in? %>
    <div class="action-like ">
      <%= link_to like_organization_path(@organization), method: :post do %>
        <i class="fa fa-thumbs-up organization-card-icon"></i>
      <% end %>
      <span class="organization-card-icon-text"><%= @organization.votes_for.size %></span>
    </div>
    <% else %>
      <div class="action-like ">
      <%= link_to new_user_session_path do %>
        <i class="fa fa-thumbs-up organization-card-icon"></i>
      <% end %>
      <span class="organization-card-icon-text"><%= @organization.votes_for.size %></span>
    </div>
  <% end %>
</div>