config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: { registrations: 'registrations' }
  ActiveAdmin.routes(self)
  get 'bookings/create'

  mount Attachinary::Engine => '/attachinary'

  resource :bookings, only: [:create]
  get 'organizations_search', to: 'organizations#search'

  resources :organizations do
    get 'organization_contact', to: 'organizations#organization_contact'
    post 'organization_contact', to: 'organizations#organization_send', as: 'organization_send'
    resources :jobs
    resources :events
  end

  post 'organizations/:id/like', to: 'organizations#like', as: 'like_organization'

  post 'articles/:id/like', to: 'articles#like', as: 'like_article'

  root to: 'pages#home'
  get 'welcome', to: 'pages#welcome'
  get 'dashboard', to: 'pages#dashboard'
  get 'about_us', to: 'pages#about_us'
  get 'developers', to: 'pages#developers'
  get 'events', to: 'pages#events', as: 'events'
  get 'jobs', to: 'pages#jobs', as: 'jobs'

  get 'articles/search', to: 'articles#search'
  get 'articles/tags/:tag', to: 'articles#by_tag'
  resources 'comments', only: [:create, :destroy]
  resources 'articles', only: [:show, :index]
end

app/views/pages/_jobs_list.html.erb
<div id="filterrific_results">
<% @jobs.each do |job| %>
<div class="col-xs-12 col-sm-6 col-md-4">
<div itemscope itemtype="http://schema.org/jobPosting" class="job-card">
<% if job.organization.logo %>
<img src="<%= cl_image_path job.organization.logo.path, height: 180, width: 350, crop: :fill%>", class='job-card-img' >
<% else %>
<%= image_tag "card_org_ngo_default.jpg", class: "job-card-img" %>
<% end %>
<div class="job-card-description">
<p itemprop="title" id="job-name"><strong><%= truncate(job.name, length: 20) %></strong></p>
<p itemprop="hiringOrganization" id="job-problem"><%= truncate(job.organization.name, length: 20) %></p>
<p itemprop="employmentType" id="job-category"><%= truncate(job.job_type, length: 20) %></p>
<p itemprop="jobLocation" itemscope itemtype="http://schema.org/Place" id="job-category"><span itemprop="address"><%= truncate(job.address, length: 20) %></span></p>
</div>
<%= link_to "", organization_job_path(job.organization.slug, job.slug) , class: "organization-card-link" %>
</div>
</div>
<% end %>
</div>

app/views/pages/about_us.html.erb
<% title "About us" %>

<div class="container-fluid" id="aboutus-wrapper">
  <div class="aboutus-content">

    <h2 class="text-center aboutus-title">Our mission</h2>
    <p class="text-justify">Feiy is a China-based international platform that connects and inspires a new generation of social dreamers. We are a hub for high-impact initiatives, to learn more about the positive solutions they create and the impact they have on our society and environment. These high-impact initiatives can also share information about events they organize and jobs they offer.</p>

    <h2 class="text-center aboutus-title">Why are we doing this?</h2>
    <p class="text-justify">Many people are doing great things out there, dedicating their lives to create a better world to come, a world that is more human-centered, eco-friendly and fair. We want to help them spread the word about their visions and purpose in order to attract more talented and motivated people to join their cause.   We also believe that more and more people are seeking ways to take part in this change. We want to connect this ambitious people with socially and environmentally driven organizations and be the first push in their journey for a better world.
    </p>

    <h2 class="text-center aboutus-title">The Story</h2>
    <p class="text-justify">Feiy is an adventure started in Shanghai in 2015 by a team of dreamers that wanted to contribute in spreading the word about meaningful events, jobs and projects in Shanghai and in China. After two years of work, discovering more and more life changing projects, meeting everyday awesome people drawing the lines of what businesses should be tomorrow, we decided to take a step further and create a platform to foster awareness and collaboration around social/ environmental impact in China.</p>

    <h2 class="text-center aboutus-title">What are high-impact initiatives?</h2>
    <p class="text-justify">We call high-impact initiatives, social enterprises, NGOs, CSR/Sustainability departments or organizations that clearly state in their mission an intention of solving or positively contribute to a social or environmental problem through their work.</p>

    <h2 class="text-center aboutus-title">What can I do on Feiy?</h2>
    <p class="text-justify">As a user I can discover amazing positive initiatives working in different fields, follow them to be updated, comment their work, or get in touch with them. I can also get involved by attending inspiring events or applying to meaningful jobs.<br>As an organization I have the opportunity to showcase my work and my impact, promote my events and job offers to a community of like-minded people.<br><br></p>
    <p class="text-center">Feiy online platform is an initiative supported by </p>
    <%= image_tag "impact-hub_logo.svg", id: "impact-hub-logo" %>
  </div>
  <div class="aboutus-sidebar hidden-xs hidden-sm">
    <div class="call-box" >
      <%= link_to "JOIN US NOW!", new_user_registration_path, class: "call-box-btn btn-feiy-primary button-cta-primary" %>
    </div>
  </div>
</div>

app/views/pages/dashboard.html.erb
<div class="dashboard-sidebar">
  <div class="dashboard-sidebar-orgname">
    <h4><%= @organization.name %></h4>
  </div>
  <div class="dashboard-sidebar-orginfo">
    <% if current_user.avatar? %>
      <%= cl_image_tag current_user.avatar.path, height: 50, width: 50, crop: :fill, gravity: :face, radius: :max, class: "avatar-style"  %>
    <% else %>
      <%= image_tag "profile_placeholder.png" %>
    <% end %>
      <h3 class="dashboard-sidebar-username">Welcome <strong><%= current_user.name %></strong></h3>
      <p class="dashboard-sidebar-usermail"><%= current_user.email %></p>
      <p class="dashboard-sidebar-admin">Verified Administrator</p>
      <%= link_to "Edit Profile", edit_user_registration_path, class: "btn btn-feiy-primary" %>
  </div>
</div>
<div class="dashboard-content">
  <% if @organization.accepted? == true %>
    <h4>Organization overview</h4>
    <div class="dashboard-content-section dasboard-content-info">
      <h5><strong>What do we do?</strong></h6>
      <p><%= @organization.problem %></p>
      <h5><strong>How do we do it?</strong></h6>
      <p><%= @organization.description %></p>
      <div class="dashboard-content-info-buttons">
      <% if policy(@organization).edit? %>
        <%= link_to "Edit", edit_organization_path(@organization), class: "btn btn-feiy-secondary" %>
      <% end %>
        <%= link_to "Delete", organization_path(@organization), method: :delete, data: {confirm: "Are you sure you want to delete your organization?"}, class: "btn btn-feiy-secondary" %>
      </div>
    </div>
    <div class="dashboard-content-section">
      <h5><strong>Your audience</strong></h5>
      <div class="dashboard-content-audience">
        <div class="organization-audience-card">
          <p class="audience-number"><%= @organization.votes_for.size %></p>
          <p class="audience-word">Followers</p>
        </div>
        <div class="organization-audience-card">
          <p class="audience-number"><%= @organization.comments.size %></p>
          <p class="audience-word">Comments</p>
        </div>
      </div>
    </div>
    <div class="dashboard-content-section dashboard-content-comments">
      <h5><strong>Follower comments</strong></h5>
      <% if @random_comment %>
        <div class="random-comment-big-card">
          <div class="random-comment-big-card-top">
            <div class="comment-big-card-useravatar">
              <% if @random_comment.user.avatar? %>
                <%= cl_image_tag @random_comment.user.avatar.path, height: 50, width: 50, crop: :fill, gravity: :face, radius: :max, class: "comment-avatar"  %>
              <% else %>
                <%= image_tag "profile_placeholder.png", style: "width: 50px" %>
              <% end %>
            </div>
            <div clas="comment-big-card-userinfo">
              <p class="comment-email"><strong><%= @random_comment.user.email %></strong></p>
              <p class="comment-date"><%= @random_comment.created_at.strftime("%B %d, %Y") %></p>
            </div>
          </div>
          <div class="random-comment-big-card-bottom">
            <p><em>"<%= @random_comment.comment %>"</em></p>
          </div>
        </div>
      <% else %>
        <div class="empty-content text-center">
          <h3>No comments</h3>
        </div>
      <% end %>
    </div>
    <div class="dashboard-content-section dashboard-content-followers">
      <h5><strong>Followers</strong></h5>
      <% if @organization.votes_for.size == 0 %>
        <div class="empty-content text-center">
          <h3>No followers</h3>
        </div>
      <% else %>
        <div class="container">
          <% @organization.votes_for.in_groups_of(3) do |group| %>
            <div class="row" style="margin-top: 20px;">
             <% group.compact.each do |vote| %>
               <div class="col-xs-12 col-sm-6 col-md-4">
                 <div class="follower-card">
                   <div class="follower-card-avatar">
                     <% if vote.voter.avatar? %>
                       <%= cl_image_tag vote.voter.avatar.path, height: 50, width: 50, crop: :fill, gravity: :face, radius: :max, class: "avatar-style"  %>
                     <% else %>
                       <%= image_tag "profile_placeholder.png", style: "width: 50px" %>
                     <% end %>
                   </div>
                   <div class="follower-card-info">
                     <p class="comment-email"><strong><%= vote.voter.email %></strong></p>
                     <p class="comment-date"><%= vote.created_at.strftime("%B %d, %Y") %></p>
                   </div>
                 </div>
                </div>
             <% end %>
            </div>
          <% end %>
        </div>
      <% end %>
    </div>
    <div class="dashboard-content-section dashboard-content-jobs">
      <div class="dashboard-title">
        <h5><strong>Jobs</strong></h5>
        <% if policy(@organization).create? %>
        <%= link_to "Add", new_organization_job_path(@organization) %>
        <% end %>
      </div>
      <% if @jobs.size == 0 %>
        <div class="empty-content text-center">
          <h3>No jobs have been created</h3>
        </div>
      <% else %>
        <div class="container">
          <div class="row">
            <% @jobs.each do |job| %>
              <div class="col-xs-12 col-sm-6 col-md-4">
                <div class="job-card">
                <% if job.organization.logo %>
                  <img src="<%= cl_image_path job.organization.logo.path, height: 180, width: 350, crop: :fill%>", class='job-card-img' >
                <% else %>
                  <%= image_tag "card_org_ngo_default.jpg", class: "job-card-img" %>
                <% end %>
                <div class="job-card-description">
                  <p id="job-name"><strong><%= truncate(job.name, length: 17) %></strong></p>
                  <p id="job-problem"><%= truncate(job.organization.name, length: 17) %></p>
                  <p id="job-category"><%= truncate(job.job_type, length: 17)%></p>
                  <p id="job-category"><%= truncate(job.address, length: 17) %></p>
                </div>
                 <%= link_to "", organization_job_path(job.organization_id, job.id) , class: "organization-card-link" %>
                </div>
              </div>
            <% end %>
          </div>
        </div>
      <% end %>
    </div>
    <div class="dashboard-content-section dashboard-content-events">
      <div class="dashboard-title">
        <h5><strong>Events</strong></h5>
        <%= link_to "Add", new_organization_event_path(@organization) %>
      </div>
      <% if @events.size == 0 %>
        <div class="empty-content text-center">
          <h3>No events have been created</h3>
        </div>
      <% else %>
        <div class="container">
          <div class="row">
            <% @events.each do |event| %>
              <div class="col-xs-12 col-sm-6 col-md-4">
           <div class="event-card">
            <% if event.organization.logo %>
              <img src="<%= cl_image_path event.organization.logo.path, height: 180, width: 350, crop: :fill%>", class='events-card-img' >
            <% else %>
              <%= image_tag "card_org_ngo_default.jpg", class: "events-card-img" %>
            <% end %>
              <div class="events-card-description">
                <p id="job-name">Hosted by <%= truncate(event.organization.name, length: 17) %></p>
                <p id="job-address"><%= truncate(event.date.strftime("%B %e, %Y, %l:%M %p ")) %></p>
              </div>
              <p class="event-hover-card text-center" id="event-name"><strong><%= event.name %></strong><br><br><%= truncate(event.content, length: 17)%></p>
              <%= link_to "", organization_event_path(event.organization_id, event.id), class: "organization-card-link" %>
            </div>
              </div>
            <% end %>
          </div>
        </div>
      <% end %>
    </div>
  <% else %>
    <div class="approve-sign text-center">
      <span>
        <h2>You're almost there!</h2>
        <h4>First, our team will approve your organization because we need to make sure that your content is aligned with our mission!</h4>

        <h4>Then you will be able to promote your great work, events and jobs to our growing community :)</h4>

        <h4>Thank you for understanding.</h4>

        <h3>
          "Genius is patience" <b>Isaac Newton</b>
          </h3>
      </span>
    </div>
  <% end %>
</div>

app/views/pages/events.html.erb
<% title "Good Events" %>
<% description "Looking to meet and engage with like-minded people, get involved in great communities and have an impact around you ? Sign up on Feiy to get updates about meaningful and worthy events in China." %>

<div class="wrapper-white">
  <div class="container-demo-title">
    <h1 class="text-center">Good Events</h1>
    <h5 class="text-center"><%= pluralize(@events.count, "Event") %></h5>
  </div>
  <div class="container">
    <div class="row">
      <% @events.each do |event| %>
        <div class="col-xs-12 col-sm-6 col-md-4">
          <div itemscope itemtype="http://schema.org/Event" class="event-card">
          <% if event.organization.logo %>
            <img itemprop="image" src="<%= cl_image_path event.organization.logo.path, height: 180, width: 350, crop: :fill%>", class='events-card-img' >
          <% else %>
            <%= image_tag "card_org_ngo_default.jpg", class: "events-card-img" %>
          <% end %>
            <div class="events-card-description">
              <p itemprop="name" id="job-name"><%= truncate(event.name, length: 17) %></p>
              <p itemprop="startDate" id="job-address"><%= event.date.strftime("%B %e, %Y, %l:%M %p ") %></p>
            </div>
            <p itemprop="location" itemscope itemtype="http://schema.org/Place" class="event-hover-card text-center" id="event-name"><strong itemprop="address">Hosted by <%= truncate(event.organization.name, length: 17) %></strong><br><br><%= truncate(event.content, length: 20)%></p>
            <%= link_to "", organization_event_path(event.organization.slug, event.slug), class: "organization-card-link" %>
          </div>
        </div>
      <% end %>
    </div>
  </div>
</div>
<br>
<br>
<br>

app/views/pages/home.html.erb
<% title "Be the change!" %>
<% description "Feiy connects people with high-impact organisations. We are a hub where inspiring projects, events and job offers meet with people decided to take action and create impact." %>

<!-- Welcome Banner -->
<div class="wrapper" id="welcome-wrapper">
  <%= render 'shared/navbar' %>
  <div class="header">
  <div class="header-welcome text-center">
    <h1>Be the change!</h1>
  </div>
  <div class="tagline-welcome text-center">
    <h3>Connect with high-impact initiatives in China and create sustainable change</h3>
  </div>
  <% unless user_signed_in? %>
  <%= link_to "Sign in", new_user_session_path, class: "btn-feiy-primary button-cta-primary" %>
  <% end %>
  </div>


  <!-- Search bar -->
  <div id="home-search">
    <%= render 'organizations/search_bar'%>
  </div>
</div>


<!-- ORGANIZATIONS -->
<div class="wrapper">
<% if @organizations.any? %>
  <div class="title-divider text-center">
    <h4>ORGANIZATIONS</h4>
  </div>
  <div class="container">
    <div class="row">
      <% @organizations.take(3).shuffle.each do |organization| %>
        <div class="col-xs-12 col-sm-6 col-md-4">
          <div class="organization-card">
          <% if organization.photo %>
            <img src="<%= cl_image_path organization.photo.path, height: 180, width: 350, crop: :fill%>" class='organization-card-img' tag="<%= organization.name %>" >
          <% else %>
            <%= image_tag "card_org_ngo_default.jpg", class: "organization-card-img" %>
          <% end %>
          <div class="organization-card-description">
            <% if organization.tags&.first&.name %>
              <p id="organization-category"><%= truncate(organization.tags&.first&.name&.upcase) %></p>
            <% end %>
            <p id="organization-name"><strong><%= truncate(organization.name, length: 20) %></strong></p>
            <p id="organization-problem"><%= truncate(organization.problem, length: 40, omission: '...') %></p>
          </div>
          <div class="organization-card-icons">
            <i class="fa fa-heart organization-card-icon"></i>
            <span class="organization-card-icon-text"><%= organization.votes_for.size %></span>
          </div>
          <%= link_to "", organization_path(organization), class: "organization-card-link" %>
          </div>
        </div>
      <% end %>
    </div>
    <div class="row">
      <div class="col-xs-12">
        <div class="more-button text-center">
          <%= link_to "More organizations", organizations_path, class: "btn-feiy-primary button-cta-primary" %>
          <% if user_signed_in? && current_user.organizations.count >= 1 %>
            <%= link_to "Promote your Organization", dashboard_path, class: "btn-feiy-primary", style: 'margin-left:16px;' %>
          <% else %>
            <%= link_to "Create Organization", new_organization_path, class: "btn-feiy-primary", style: 'margin-left:16px;' %>
          <% end %>
        </div>
      </div>
    </div>
  </div>
<% else %>
<div class="wrapper" id="call-to-action-wrapper">
  <%= link_to "JOIN US NOW!", new_user_registration_path, class: "btn-feiy-primary button-cta-primary" %>
</div>
<% end %>

<!-- ARTICLES -->
<% if @articles.any? %>
  <div class="title-divider text-center">
    <h4>STORIES</h4>
  </div>
  <div class="container">
    <div class="row">
      <div class="col-xs-12 col-sm-12 col-md-8">
        <%= link_to(article_path(@articles.first), class: 'home-page-link') do %>
          <% if @articles.first.photo %>
            <div class="article_card_main_page", style='background-image: url(<%= cl_image_path @articles.first&.photo&.path, height: 455, width: 750, crop: :fill  %>); background-size: cover;' >
                <div class="home-main-article-description">
                  <p class="article-category"><%= @articles.first&.tags&.first %></p>
                  <p class="main-article-title"><strong><%= truncate(@articles.first.title, length: 100)%></strong></p>
                </div>
            </div>
          <% else %>
            <div class="article_card_main_page">
                <div class="home-main-article-description">
                  <p class="article-category"><%= @articles.first&.tags&.first %></p>
                  <p class="main-article-title"><strong><%= truncate(@articles.first.title, length: 100)%></strong></p>
                </div>
            </div>
          <% end %>
        <% end %>
      </div>

      <div class="col-xs-12 col-sm-12 col-md-4">
        <% @articles.drop(1).each do |article| %>
          <%= link_to(article_path(article), class: 'home-page-link') do %>
            <% if article.photo %>
              <div class="article-card-side", style='background-image: url(<%= cl_image_path  article&.photo&.path, height: 455, width: 750, crop: :fill  %>); background-size: cover;' >
                <div class="article-card-header-side">
                  <p class="article_side_card_title"><strong><%= truncate(article.title, length: 100) %></strong></p>
                </div>
              </div>
            <% else %>
              <div class="article-card-side" >
                <div class="article-card-header-side">
                  <p class="article_side_card_title"><strong><%= truncate(article.title, length: 100) %></strong></p>
                </div>
              </div>
            <% end %>
          <% end %>
        <% end %>
      </div>
    </div>
    <div class="row">
      <div class="col-xs-12">
        <div class="more-button text-center">
          <%= link_to "More stories", articles_path, class: "btn-feiy-primary button-cta-primary" %>
        </div>
      </div>
    </div>
  </div>
<% end %>


<!-- JOBS -->
<% if @jobs %>
  <div class="title-divider text-center" id="title-padding" >
    <h4>JOBS</h4>
  </div>
  <div class="container">
    <div class="row">
      <% if @jobs.count == 1 %>
        <% @jobs.take(3).shuffle.each do |job| %>
          <div class="col-xs-12 col-sm-6 col-md-4 center-block" style="float: none;">
            <div class="job-card">
            <% if job.organization.logo %>
              <img src="<%= cl_image_path job.organization.logo.path, height: 180, width: 350, crop: :fill%>" class='job-card-img' tag="<%= truncate(job.organization.name, length: 20) %>" >
            <% else %>
              <%= image_tag "card_org_ngo_default.jpg", class: "job-card-img" %>
            <% end %>
            <div class="job-card-description">
              <p id="job-name"><%= truncate(job.name) %></p>
              <p id="job-problem"><%= truncate(job.organization.name)%></p>
              <p id="job-category"><%= truncate(job.job_type)%></p>
              <p id="job-category"><%= truncate(job.address) %></p>
            </div>
             <%= link_to "", organization_job_path(job.organization_id, job.id) , class: "organization-card-link" %>
            </div>
          </div>
        <% end %>
      <% else %>
      <% @jobs.take(3).shuffle.each do |job| %>
        <div class="col-xs-12 col-sm-6 col-md-4">
          <div class="job-card">
          <% if job.organization.logo %>
            <img src="<%= cl_image_path job.organization.logo.path, height: 180, width: 350, crop: :fill%>" class='job-card-img' tag="<%= truncate(job.organization.name, length: 20) %>" >
          <% else %>
            <%= image_tag "card_org_ngo_default.jpg", class: "job-card-img" %>
          <% end %>
          <div class="job-card-description">
            <p id="job-name"><%= truncate(job.name) %></p>
            <p id="job-problem"><%= truncate(job.organization.name)%></p>
            <p id="job-category"><%= truncate(job.job_type)%></p>
            <p id="job-category"><%= truncate(job.address) %></p>
          </div>
           <%= link_to "", organization_job_path(job.organization_id, job.id) , class: "organization-card-link" %>
          </div>
        </div>
      <% end %>
      <% end %>
    </div>
    <div class="row">
      <div class="col-xs-12">
        <div class="more-button text-center">
          <%= link_to "More jobs", jobs_path, class: "btn-feiy-primary button-cta-primary" %>
          <% unless user_signed_in? && current_user.organizations.count == 1 %>
            <%= link_to "Promote a Job", new_organization_path, class: "btn-feiy-primary", style: 'margin-left:16px;' %>
          <% else %>
            <%= link_to "Promote a Job", new_organization_job_path(current_user.organizations.first), class: "btn-feiy-primary", style: 'margin-left:16px;' %>
          <% end %>
        </div>
      </div>
    </div>
  </div>
<% end %>


<!-- EVENTS -->
<% if @events %>
  <div class="title-divider text-center" id="title-padding" >
    <h4>EVENTS</h4>
  </div>
  <div class="container">
    <div class="row">
      <% @events.take(6).each  do |event| %>
        <div class="col-xs-12 col-sm-6 col-md-4">
          <div class="event-card">
          <% if event.organization.logo %>
            <img src="<%= cl_image_path event.organization.logo.path, height: 180, width: 350, crop: :fill%>" class='events-card-img' tag="<%= event.organization.name %>" >
          <% else %>
            <%= image_tag "card_org_ngo_default.jpg", class: "events-card-img" %>
          <% end %>
            <div class="events-card-description">
              <p id="job-problem"><%= truncate(event.name) %></p>
              <p id="job-category"><%= truncate(event.date.strftime("%B %e, %Y, %l:%M %p ")) %></p>
            </div>
            <p class="event-hover-card text-center" id="event-name">Hosted by <%= event.organization.name %><br><br><%= truncate(event.content)%></p>
            <%= link_to "", organization_event_path(event.organization_id, event.id), class: "organization-card-link" %>
          </div>
        </div>
      <% end %>
    </div>
    <div class="row">
      <div class="col-xs-12">
        <div class="more-button text-center">
          <%= link_to "More events", events_path, class: "btn-feiy-primary button-cta-primary" %>
          <% unless user_signed_in? && current_user.organizations.count == 1 %>
            <%= link_to "Promote an Event", new_organization_path, class: "btn-feiy-primary", style: 'margin-left:16px;' %>
          <% else %>
            <%= link_to "Promote an Event", new_organization_event_path(current_user.organizations.first), class: "btn-feiy-primary", style: 'margin-left:16px;' %>
          <% end %>
        </div>
      </div>
    </div>
  </div>
<% end %>


<!-- FEATURES -->
<div id="features-section">
<div id="features-img">
  <div class="title-divider text-center">
    <h4 class="feiy-feature-title">HOW FEIY WORKS</h4>
  </div>
  <div class="container">
    <div class="row">
      <div class="col-xs-12 col-sm-4">
        <div class="features text-center">
          <%= image_tag "home-features-search.png", class: "feiy-feature-img" %>
          <div class="feiy-feature-text">
            <h4>EXPLORE</h4>
            <h5>Be inspired & discover the actors of change</h5>
          </div>
        </div>
      </div>
      <div class="col-xs-12 col-sm-4">
        <div class="features text-center">
          <%= image_tag "home-features-book.png", class: "feiy-feature-img" %>
          <div class="feiy-feature-text">
            <h4>JOBS</h4>
            <h5>Find good jobs & start a meaningful career</h5>
          </div>
        </div>
      </div>
       <div class="col-xs-12 col-sm-4">
        <div class="features text-center">
          <%= image_tag "home-features-like.png", class: "feiy-feature-img" %>
          <div class="feiy-feature-text">
            <h4>EVENTS</h4>
            <h5>Go to events & meet like minded people</h5>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>
</div>


<!-- Bottomer Wrapper -->
<% unless user_signed_in? %>
  <div class="wrapper" id="call-to-action-wrapper">
    <%= link_to "JOIN US NOW!", new_user_registration_path, class: "btn-feiy-primary button-cta-primary" %>
  </div>
<% end %>
</div>

app/views/pages/jobs.html.erb
<% title "Good Jobs" %>
<% description "You want to start a meaningful career and be the change? Looking for a job with impact on Feiy. Need to find passionate and changemakers employees ? Post your offer on Feiy to get in touch with people that want to change the world." %>

<div class="wrapper-white">
  <div class="container-demo-title">
    <h1 class="text-center">Good Jobs</h1>
    <h5 class="text-center"><%= pluralize(@jobs.count, "Job") %></h5>
    <%= form_for_filterrific @filterrific do |f| %>
      <div class="text-center">
        Sort by:
        <%= f.select(
          :with_job_type,
          @filterrific.select_options[:job_types],
          { include_blank: '- All categories -' },
          class: 'text-search-field'
        ) %>
      </div>
    <% end %>
  </div>
  <div class="container">
    <div class="row">
      <div class="more-button text-center" style="margin-top: 48px;">
        <% unless user_signed_in? && current_user.organizations.count == 1 %>
          <%= link_to "Looking for volunteers", new_organization_path, class: "btn-feiy-primary " %>
        <% else %>
          <%= link_to "Looking for volunteers", new_organization_job_path(current_user.organizations.first), class: "btn-feiy-primary " %>
        <% end %>
        <% unless user_signed_in? && current_user.organizations.count == 1 %>
          <%= link_to "Looking for an associate", new_organization_path, class: "btn-feiy-primary " %>
        <% else %>
          <%= link_to "Looking for an associate", new_organization_job_path(current_user.organizations.first), class: "btn-feiy-primary " %>
        <% end %>
        <% unless user_signed_in? && current_user.organizations.count == 1 %>
          <%= link_to "Looking for an employee", new_organization_path, class: "btn-feiy-primary " %>
        <% else %>
          <%= link_to "Looking for an employee", new_organization_job_path(current_user.organizations.first), class: "btn-feiy-primary " %>
        <% end %>
      </div>
    </div>
    <div class="row">
      <%= render(
        partial: 'pages/jobs_list',
        locals: { jobs: @jobs }
      ) %>
    </div>
  </div>
</div>

app/views/pages/jobs.js.erb
<% js = escape_javascript(
  render(partial: 'pages/jobs_list', locals: { jobs: @jobs })
) %>
$("#filterrific_results").html("<%= js %>");

app/views/pages/welcome.haml
- title "Thank you for joining"
.container-fluid.welcome-segment
  %h1 Welcome! We are happy to have you with us.
  %h3 Maybe you have an organization, a job or an event to promote?
  %h3 Click on the link below, you're just a few tiny steps away!
  %br
  = link_to "Create an organization", new_organization_path, class: 'btn-feiy-primary'