config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: { registrations: 'registrations' }
  ActiveAdmin.routes(self)
  get 'bookings/create'

  mount Attachinary::Engine => '/attachinary'

  resource :bookings, only: [:create]
  get 'organizations_search', to: 'organizations#search'

  resources :organizations do
    get 'organization_contact', to: 'organizations#organization_contact'
    post 'organization_contact', to: 'organizations#organization_send', as: 'organization_send'
    resources :jobs
    resources :events
  end

  post 'organizations/:id/like', to: 'organizations#like', as: 'like_organization'

  post 'articles/:id/like', to: 'articles#like', as: 'like_article'

  root to: 'pages#home'
  get 'welcome', to: 'pages#welcome'
  get 'dashboard', to: 'pages#dashboard'
  get 'about_us', to: 'pages#about_us'
  get 'developers', to: 'pages#developers'
  get 'events', to: 'pages#events', as: 'events'
  get 'jobs', to: 'pages#jobs', as: 'jobs'

  get 'articles/search', to: 'articles#search'
  get 'articles/tags/:tag', to: 'articles#by_tag'
  resources 'comments', only: [:create, :destroy]
  resources 'articles', only: [:show, :index]
end

app/models/organization.rb
class Organization < ApplicationRecord
  extend FriendlyId
  friendly_id :name, use: :history

  acts_as_taggable
  scope :accepted, -> { where(accepted?: true) }
  has_attachment :logo, accept: [:jpg, :png, :gif]
  has_attachment :photo, accept: [:jpg, :png, :gif]
  acts_as_commentable
  acts_as_votable
  belongs_to :user
  has_many :events, dependent: :destroy
  has_many :jobs, dependent: :destroy
  validates :user_is_a_representative, presence: true

  def should_generate_new_friendly_id?
    name_changed?
  end

  def slug_candidates
    [
      :name,
      [:name, :created_at],
      [:name, :description, :created_at]
    ]
  end
end

app/controllers/organizations_controller.rb
class OrganizationsController < ApplicationController
  skip_before_action :authenticate_user!, only: [:index, :show, :search]
  before_action :find_organization, only: [:edit, :update, :show, :destroy, :like]

  def index
    @organizations = Organization.where(accepted?: true)
  end

  def search
    @organizations = Organization.where(accepted?: true)

    if params[:name] != ""
      @organizations = @organizations.where("name = ?", params[:name])
    end

    if params[:category] != ""
      @organizations = @organizations.tagged_with(params[:category])
    end
  end

  def new
    @organization = Organization.new
  end

  def create
    @organization = Organization.new(organization_params)
    @organization.user_id = current_user.id
    @organization = update_tag(tag_params[:tags]) if tag_params[:tags]
    if @organization.save
      mixpanel_notify(@organization, 'Organization Created') 
      redirect_to dashboard_path
    else
      render :new
    end
  end

  def edit
    authorize @organization
  end

  def update
    authorize @organization
    @organization.update(organization_params)
    @organization = update_tag(tag_params[:tags]) if tag_params[:tags]
    @organization.user_id = current_user.id

    if @organization.save
      mixpanel_notify(@organization, 'Organization Updated')
      redirect_to organization_path(@organization)
    else
      render :new
    end
  end

  def show
    tag = @organization&.tags&.first&.name
    @organizations = Organization.accepted.tagged_with(tag).where.not(id: params[:id])
    if @organizations.any?
      @suggested_organizations_shuffled = @organizations.shuffle
    else
      @suggested_organizations_shuffled = []
    end
    events = @organization.events
    @events = events.where('date >= ?', Date.today).order(date: :asc)
  end

  def destroy
    authorize @organization
    @organization.destroy
    flash[:notice] = "Your organization has been deleted!"
    redirect_to root_path
  end

  def like
    @organization.liked_by current_user
    @likes = @organization.votes_for.size
    redirect_to organization_path(@organization)
  end

  def organization_contact
    @organization = Organization.find(params[:organization_id])
  end

  def organization_send
    @sender = current_user
    @organization = Organization.find(params[:organization_id])
    @body = params[:body]
    OrganizationMailer.organization_contact_email(@organization, @sender, @body).deliver
    flash[:notice] = "Your message has been sent!"
    redirect_to organization_path(@organization)
  end

  private

  def find_organization
    @organization = Organization.friendly.find(params[:id])
    if params[:id] != @organization.slug && params[:id]&.to_i != @organization.id
      return redirect_to organization_path( @organization), status: :moved_permanently
    end
  end

  def update_tag(tag)
    @organization.tag_list.remove(@organization.tags.map(&:name))
    @organization.tag_list.add(ActsAsTaggableOn::Tag.find_by(name: tag))
    @organization
  end

  def tag_params
    params.require(:organization).permit(:tags)
  end

  def organization_params
    params.require(:organization).permit(:name, :problem, :description, :website,
      :email, :address, :photo, :logo, :user_is_a_representative,
      :slug, :accepted?)
  end

  def mixpanel_notify(organization, event)
    MIXPANEL.track(organization.user_id, event, {
      content: organization.class.to_s,
      name: organization.name,
      address: organization.address,
      website: organization.website

    })
  end
end

app/helpers/organizations_helper.rb
module OrganizationsHelper
end

app/views/organizations/_form.html.erb
<%= simple_form_for(@organization) do |f| %>
  <div class="form-inputs">
    <%= f.input :logo, as: :attachinary %>
    <%= f.input :name %>
    <%= f.input :photo, label: "Background image", as: :attachinary %>
    <%= f.input :problem, label: "Cause" %>
    <%= f.input :address, label: "Location" %>
    <%= f.input :description, as: :text, :input_html => {:rows => 10}  %>
    <%= f.input :email, label: "E-mail" %>
    <%= f.input :website %>
    <%= f.input :tags, collection: ActsAsTaggableOn::Tag.all.map(&:name), value: (@organization&.tags&.first&.name || 'Tag your organization') %>
  </div>
    <%= f.input :user_is_a_representative, inline_label: 'I am a representative of this organization', error: 'Only representatives can add organizations', error_html: { id: 'representative_error'}   %>
  <div class="form-actions">
    <%= f.button :submit, "Submit", class: "btn-feiy-primary" %>
  </div>
<% end %>

app/views/organizations/_search_bar.html.erb
<!-- Search bar -->
<%= form_tag organizations_search_path, method: :get do %>
<%= text_field_tag 'name', params[:name], placeholder: "  Search organizations", class: "text-search-field" %>
<%= select_tag(:category, options_for_select([['Education'], ['Fashion'], ['Waste'], ['Health'], ['Environment'], ['Inclusion'],['Community']]), include_blank: "All categories", class: "text-search-dropdown")%>

<%= submit_tag 'Search', class: "btn-feiy-rec-white"%>
<% end %>

app/views/organizations/edit.html.erb
<div class="form-container">
  <h2>Update your organization:</h2>
  <%= render 'form' %>
</div>

app/views/organizations/index.html.erb
<% title "High-impact initiatives in China" %>
<% description "On Feiy discover who are China changemakers, social enterprises, initiatives or networks that are having a positive impact on our lives, developing innovative and alternative solutions to create a better and more sustainable world." %>

<div class="wrapper index-search-wrapper">
  <div class="index-search-header">
    <div class="index-search-header-welcome text-center">
      <h1>Discover the community<br>of high-impact initiatives<br>in China</h1>
    </div>
  </div>
  <!-- Search bar -->
  <div  class="results-search" >
    <%= render 'search_bar'%>
  </div>
</div>


<!-- ORGANIZATIONS SEARCH RESULTS -->
<div class="container">
  <div class="row">
    <% @organizations.each do |organization| %>
      <div class="col-xs-12 col-sm-6 col-md-4">
        <div class="organization-card">
        <% if organization.photo %>
          <img src="<%= cl_image_path organization.photo.path, height: 180, width: 350, crop: :fill%>" class='organization-card-img' tag="<%= organization.name %>" >
        <% else %>
          <%= image_tag "card_org_ngo_default.jpg", class: "organization-card-img" %>
        <% end %>
        <div class="organization-card-description">
          <% if organization.tags&.first&.name %>
            <p id="organization-category"><%= truncate(organization.tags&.first&.name&.capitalize, length: 20) %></p>
          <% end %>
          <p id="organization-name"><strong><%= truncate(organization.name, length: 20) %></strong></p>
          <p id="organization-problem"><%= truncate(organization.problem, length: 20) %></p>
        </div>
        <div class="organization-card-icons">
          <i class="fa fa-heart organization-card-icon"></i>
          <span class="organization-card-icon-text"><%= organization.votes_for.size %></span>
        </div>
        <%= link_to "", organization_path(organization), class: "organization-card-link" %>
        </div>
      </div>
    <% end %>
  </div>
</div>

app/views/organizations/new.html.erb
<div class="form-container">
  <h2>Create your organization</h2>
  <%= render 'form' %>
</div>

app/views/organizations/organization_contact.html.erb
<div class="form-container" id="message-form">
  <h2>Message</h2>
  <%= form_for organization_organization_contact_path(@organization) do |f| %>
    <div class="form-inputs">
      <textarea type="text" name="body" class="textarea"></textarea>
    </div>
    <div class="form-actions">
      <%= f.submit "Send", class: "btn-feiy-primary" %>
    </div>
  <% end %>
</div>

app/views/organizations/search.html.erb
<% title "Search Organizations" %>

<div class="wrapper index-search-wrapper">
  <div class="index-search-header">
    <div class="index-search-header-welcome text-center">
      <h1>Discover the community<br>of high-impact initiatives<br>in China</h1>
    </div>
  </div>
  <!-- Search bar -->
  <div  class="results-search" >
    <%= render 'search_bar'%>
  </div>
</div>


<!-- ORGANIZATIONS SEARCH RESULTS -->
<div class="text-center results-message">
<% unless @organizations.present? %>
  <h4>We haven't found any organization matching your search! Please try again!</h4>
<% end %>
</div>
<div class="container">
  <div class="row">
    <% @organizations.each do |organization| %>
      <div class="col-xs-12 col-sm-6 col-md-4">
        <div class="organization-card">
        <% if organization.photo %>
          <img src="<%= cl_image_path organization.photo.path, height: 180, width: 350, crop: :fill%>" class='organization-card-img' tag="<%= organization.name %>" >
        <% else %>
          <%= image_tag "card_org_ngo_default.jpg", class: "organization-card-img" %>
        <% end %>
        <div class="organization-card-description">
          <% if organization.tags.present? %>
            <p id="organization-category"><%= organization&.tags&.first&.name %></p>
          <% end %>
          <p id="organization-name"><strong><%= organization.name %></strong></p>
          <p id="organization-problem"><%= truncate(organization.problem) %></p>
        </div>
        <div class="organization-card-icons">
          <i class="fa fa-heart organization-card-icon"></i>
          <span class="organization-card-icon-text"><%= organization.votes_for.size %></span>
        </div>
        <%= link_to "", organization_path(organization), class: "organization-card-link" %>
        </div>
      </div>
    <% end %>
  </div>
</div>

app/views/organizations/show.html.erb
<% title @organization.name.capitalize %>

<div itemscope itemtype="http://schema.org/Organization">
  <% if @organization.photo %>
    <div class="org-show-banner">
      <%= cl_image_tag @organization.photo.path, width: 1440, height: 450, crop: :fill %>
    </div>
  <% else %>
    <div class="org-show-grey-banner"></div>
  <% end %>

  <% if @organization.logo? %>
    <div class="org-show-banner-logo-placeholder">
      <div class="round-logo-placeholder">
        <%= cl_image_tag @organization.logo.path, width: 100, height: 100, crop: :pad, radius: :max %>
      </div>
    </div>
  <% end %>

  <div class="org-show-banner-content">
    <div class="org-show-banner-content-info">
      <h1 itemprop="name"><%= @organization.name %></h1>
      <p><strong>Category:</strong> <%= @organization.tags.first&.name&.capitalize %></p>
      <p><strong><%= @organization.votes_for.size %> Likes</strong></p>
    </div>
      <div class="org-show-button-holder">
        <% if user_signed_in? && @organization.user_id == current_user.id %>
          <%= link_to edit_organization_path(@organization), method: :get do %>
            <%= image_tag "editor.png", class: "org-show-update" %>
          <% end %>
        <% end %>
        <%= link_to organization_organization_contact_path(@organization) do %>
          <%= image_tag "mail.png", class: "org-show-update" %>
        <% end %>
        <% if user_signed_in? %>
          <div class="action-like ">
            <%= link_to like_organization_path(@organization), method: :post do %>
              <%= image_tag "praise.png", class: "org-show-update" %>
            <% end %>
          </div>
        <% else %>
          <div class="action-like ">
            <%= link_to new_user_session_path do %>
              <%= image_tag "praise.png", class: "org-show-update" %>
            <% end %>
          </div>
        <% end %>
      </div>
  </div>

  <div class="org-show-body-content">
    <h4><strong>Our Mission</strong></h4>
    <p itemprop="description" class="text-justify"><%= simple_format(@organization.description) %></p>
    <h4><strong>What problem we solve?</strong></h4>
    <p class="text-justify"><%= simple_format(@organization.problem) %></p>
    <h4><strong>Locations</strong></h4>
    <p itemprop="address"><%= @organization.address %></p>
    <% if @organization.website.present? %>
      <h4><strong>Website</strong></h4>

      <% url = @organization.website %>
      <% unless url[/\Ahttp:\/\//] || url[/\Ahttps:\/\//] %>
        <% url = "http://#{url}" %>
      <% end %>

      <p><%= link_to url, url, class: "organization-website-link" %></p>
    <% end %>
  </div>
</div>

<!-- You may also like -->
<div class="container text-center">
  <div class="title-divider text-center" id="title-padding">
  <% unless @organization.jobs.empty? && @events.empty? %>
    <h4>You may also like</h4>
    <% if user_signed_in? && @organization.user_id == current_user.id %>
      <div class="organization-add-info-buttons text-center">
        <%= link_to "Add a job", new_organization_job_path(@organization), method: :get, class: 'btn-feiy-organization-action'  %>
        <%= link_to "Add a event", new_organization_event_path(@organization), method: :get, class: 'btn-feiy-organization-action'  %>
      </div>
    <% end %>
  <% end %>
  </div>
</div>

<!-- Jobs Section -->
<div class="container">
  <div class="row">
    <% @organization.jobs.each do |job| %>
      <div class="col-xs-12 col-sm-6 col-md-4">
          <div class="job-card">
          <% if job.organization.logo %>
            <img src="<%= cl_image_path job.organization.logo.path, height: 180, width: 350, crop: :fill%>" class='job-card-img' tag="<%= truncate(job.organization.name, length: 20) %>" >
          <% else %>
            <%= image_tag "home_bg.png", class: "job-card-img" %>
          <% end %>
          <div class="job-card-description">
            <p id="job-name"><strong><%= truncate(job.name, length: 20) %></strong></p>
            <p id="job-problem"><%= truncate(job.organization.name, length: 20) %></p>
            <p id="job-category"><%= truncate(job.job_type, length: 20) %></p>
            <p id="job-category"><%= truncate(job.address, length: 20) %></p>
          </div>
           <%= link_to "", organization_job_path(job.organization_id, job.id) , class: "organization-card-link" %>
          </div>
      </div>
    <% end %>
  </div>
</div>

<!-- Events Section -->
<div class="container">
  <div class="row">
    <% @events.each do |event| %>
      <div class="col-xs-12 col-sm-6 col-md-4">
        <div class="event-card">
        <% if event.organization.logo %>
          <img src="<%= cl_image_path event.organization.logo.path, height: 180, width: 350, crop: :fill%>" class='events-card-img' tag="<%= event.organization.name %>" >
        <% else %>
          <%= image_tag "home_bg.png", class: "events-card-img" %>
        <% end %>
          <div class="events-card-description">
            <p id="job-problem"><strong><%= truncate(event.name, length: 20) %></strong></p>
            <p id="job-address"><%= event.date.strftime("%B %e, %Y, %l:%M %p ") %></p>
          </div>
          <p class="event-hover-card text-center" id="event-name">Hosted by <%= event.organization.name %><br><br><%= truncate(event.content, length: 20)%></p>
          <%= link_to "", organization_event_path(event.organization_id, event.id), class: "organization-card-link" %>
        </div>
      </div>
    <% end %>
  </div>
</div>

<% if user_signed_in? && @organization.user_id == current_user.id %>
<div class="row" id="emptypadding-footer"></div>
<% else %>
<% end %>

<!-- OTHER ORGANIZATIONS -->
<% if @suggested_organizations_shuffled.empty? %>
  <div></div>
<% else %>
  <div class="title-divider text-center" id="title-padding">
    <h4>Similar organizations</h4>
  </div>
  <div class="container">
    <div class="row">
      <% @suggested_organizations_shuffled.each do |organization| %>
        <div class="col-xs-12 col-sm-6 col-md-4">
          <div class="organization-card">
          <% if organization.photo %>
            <img src="<%= cl_image_path organization.photo.path, height: 180, width: 350, crop: :fill%>" class='organization-card-img' tag="<%= organization.name %>" >
          <% else %>
            <%= image_tag "home_bg.png", class: "organization-card-img" %>
          <% end %>
          <div class="organization-card-description">
            <p id="organization-name"><strong><%= truncate(organization.name, length: 20) %></strong></p>
            <p id="organization-problem"><%= truncate(organization.problem, length: 20) %></p>
            <% if organization.tags&.first&.name %>
              <p id="organization-category"><%= truncate(organization.tags&.first&.name, length: 20) %></p>
            <% end %>
          </div>
          <div class="organization-card-icons">
            <i class="fa fa-heart organization-card-icon"></i>
            <span class="organization-card-icon-text"><%= organization.votes_for.size %></span>
          </div>
          <%= link_to "", organization_path(organization), class: "organization-card-link" %>
          </div>
        </div>
      <% end %>
    </div>
  </div>
<% end %>

<!-- FOLLOWERS -->
<% if @organization.votes_for.count == 0 %>
  <div></div>
<% else %>
  <div class="title-divider text-center" id="title-padding">
    <h4>FOLLOWERS</h4>
  </div>
  <div class="container">
    <div class="row" style="margin-top: 20px;">
      <% @organization.votes_for.each do |follower| %>
        <div class="col-xs-12 col-sm-6 col-md-4">
          <div class="follower-card">
            <div class="follower-card-avatar">
              <% if follower.voter.avatar? %>
                <%= cl_image_tag follower.voter.avatar.path, height: 50, width: 50, crop: :fill, gravity: :face, radius: :max, class: "avatar-style" %>
              <% else %>
                <%= image_tag "profile_placeholder.png", style: "width: 50px" %>
              <% end %>
            </div>
            <div class="follower-card-info">
              <p class="comment-email"><strong><%= follower.voter.name %></strong></p>
              <p class="comment-date"><%= follower.voter.created_at.strftime("%B %d, %Y") %></p>
            </div>
          </div>
        </div>
      <% end %>
    </div>
  </div>
<% end %>

<!-- comment function -->
<%= render('comments/form', locals: {commentable: @organization}) %>
<%= render('comments/comments', locals: {commentable: @organization}) %>